config/routes.rb
Rails.application.routes.draw do
  root to: 'shares#index'

  resources :shares
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/share.rb
class Share < ApplicationRecord
  YOUTUBE_FORMAT_REGEXP = /\Ahttps:\/\/www\.youtube\.com\/watch\?v=([a-zA-Z0-9_-]*)\Z/

  paginates_per 5
  default_scope -> { order(created_at: :desc) }

  belongs_to :user

  validates_presence_of :title, :description, :url
  validates_format_of :url, with: YOUTUBE_FORMAT_REGEXP, message: 'is not youtube url'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shares

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from StandardError do |exception|
    render :file => 'public/500.html'
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :set_share, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @shares = Share.includes(:user).all.page(params[:page])
  end

  def show
    @share = Share.includes(:user).find(params[:id])
  end

  def new
    @share = Share.new
  end

  def create
    @share = current_user.shares.create(share_params)

    respond_to do |format|
      if @share.save
        format.html { redirect_to @share, notice: 'Share was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @share.update(share_params)
        format.html { redirect_to @share, notice: 'Share was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @share.destroy
    respond_to do |format|
      format.html { redirect_to shares_url, notice: 'Share was successfully destroyed.' }
    end
  end

  private
    def set_share
      @share ||= current_user.shares.find(params[:id])
    end

    def share_params
      params.require(:share).permit(:title, :description, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shares_helper.rb
module SharesHelper
  def youtube_video(youtube_url, css_class = 'embed-responsive-item')
    youtube_params = youtube_url.split("?").second
    youtube_id = youtube_params.split("&").first.split('=').last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}", class: css_class, alt: 'Video loading . . .!')
  end

  def editable?(share)
    current_user && current_user.id == share.user_id
  end
end

app/views/layouts/_header.html.erb
<nav class="nav navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to(root_path, class: "navbar-brand") do %>
        <span><i class="fa fa-home"></i></span>Funny Movie
      <% end %>
    </div>
    <ul>
      <% if current_user.present? %>
        <li><a class="user-info"> <%= current_user.email %> </a></li>
        <li><%= link_to "Share Video", new_share_path, class: "navbar-text navbar-link" %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareYoutubeVideo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <%= render 'layouts/header' %>

  <body>
    <div class="container">
      <br>
      <% if notice %><div class="alert alert-success"><p><%= notice %></p></div> <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shares/_form.html.erb
<%= form_with(model: share, local: true) do |form| %>
  <% if share.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
      <% share.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/shares/_share.html.erb
<div class="row share">
  <div class="col text-right">
    <div class="embed-responsive embed-responsive-16by9">
      <%= youtube_video(share.url) %>
    </div>
  </div>

  <div class="col text-left">
    <h2 class="title"><%= link_to share.title, share %></h2>
    <h6 class="sharer">Shared By: <%= share.user.email %></h6>
    <div class="description">
      <h5>Description</h5>
      <%= share.description %>
    </div>
  </div>
</div>

app/views/shares/edit.html.erb
<h1>Editing Share</h1>

<%= render 'form', share: @share %>

<br>
<p>
  <%= link_to 'Show', @share %> |
  <%= link_to 'Back', shares_path %>
</p>

app/views/shares/index.html.erb
<div class="shares">
  <% @shares.each do |share| %>
    <%= render partial: 'share', locals: {share: share} %>
  <% end %>

  <%= paginate @shares, window: 2, class: 'pagination' %>
</div>

app/views/shares/new.html.erb
<h1>New Share</h1>

<%= render 'form', share: @share %>

<br>
<p><%= link_to 'Back', shares_path %></p>

app/views/shares/show.html.erb
<div class="shares">
  <%= render partial: 'share', locals: {share: @share} %>

  <p>
    <%= link_to 'Edit |', edit_share_path(@share) if editable?(@share) %>
    <%= link_to 'Back', shares_path %>
  </p>
</div>